name: "Lint PR title"

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

permissions:
  pull-requests: write

jobs:
  validate_pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |-
            feat
            fix
            chore
          scopes: |
            core
            ui
            JIRA-\d+
          wip: true
          requireScope: true
          githubBaseUrl: ${{ github.api_url }}

# The following terminology helps to understand the configuration options:

# feat(ui): Add `Button` component
# ^    ^    ^
# |    |    |__ Subject
# |    |_______ Scope
# |____________ Type
